SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE playlist_songs;
TRUNCATE TABLE playlists;
TRUNCATE TABLE songs;

SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS playlist_songs;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS songs;